apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-aigovkit
  labels:
    app: {{ .Release.Name }}-aigovkit
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-aigovkit
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-aigovkit
    spec:
      containers:
        - name: aigovkit
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
